[package]
name = "mp_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "6.2.0"
rayon = "1.8.1"
rand = "0.8.5"
ndarray-rand = "0.14.0"
ndarray = { version="0.15.6", features=["rayon"] }